### ISSUE TITLE
question about returning multiple yaml docs from a function

### ISSUE THREAD

**Issue by jrmyr** [k14s/ytt#152]
Hello,

I would like to have 2 yaml docs inside a function. For example like this:
```yaml
#@ def twodoc_yaml():
doc1:
  key1: val1
---
doc2:
  key1: val1
#@ end
```
When I try to generate from this file with `ytt -f test.yaml`, I get an error:
```bash
ytt: Error: 
- (p) expected to find node tag 1 when unwinding (backtrace: goroutine 1 [running]:
    in twodoc_yaml
      test.yaml:4 | ---
    in <toplevel>
      test.yaml:9 | --- #@ twodoc_yaml()

    reason:
     runtime/debug.Stack(0x1518800, 0x14e43c0, 0xc000170b90)
        runtime/debug/stack.go:24 +0x9d
     github.com/k14s/ytt/pkg/template/core.ErrWrapper.func1.1(0xc000126848)
        github.com/k14s/ytt@/pkg/template/core/errs.go:20 +0x158
     panic(0x14e43c0, 0xc000170b90)
        runtime/panic.go:679 +0x1b2
     github.com/k14s/ytt/pkg/template.(*EvaluationCtx).unwindToTag(0xc000104a00, 0x1)
        github.com/k14s/ytt@/pkg/template/evaluation_ctx.go:268 +0x105
     github.com/k14s/ytt/pkg/template.(*EvaluationCtx).startNode(0xc000104a00, 0x7, 0x7, 0x0)
        github.com/k14s/ytt@/pkg/template/evaluation_ctx.go:220 +0x199
     github.com/k14s/ytt/pkg/template.(*EvaluationCtx).TplStartNode(0xc000104a00, 0xc0000b9180, 0xc00013bb60, 0xc000170b80, 0x1, 0x1, 0x0, 0x0, 0x0, 0x16ec360, ...)
        github.com/k14s/ytt@/pkg/template/evaluation_ctx.go:183 +0xb3
     github.com/k14s/ytt/pkg/template.(*CompiledTemplate).tplStartNode(0xc0000aaa80, 0xc0000b9180, 0xc00013bb60, 0xc000170b80, 0x1, 0x1, 0x0, 0x0, 0x0, 0x16ec360, ...)
        github.com/k14s/ytt@/pkg/template/compiled_template.go:278 +0xb1
     github.com/k14s/ytt/pkg/template/core.ErrWrapper.func1(0xc0000b9180, 0xc00013bb60, 0xc000170b80, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        github.com/k14s/ytt@/pkg/template/core/errs.go:25 +0xff
     go.starlark.net/starlark.(*Builtin).CallInternal(0xc00013bb60, 0xc0000b9180, 0xc000170b80, 0x1, 0x1, 0x0, 0x0, 0x0, 0x1a3bc00, 0x1b3f6d0, ...)
        go.starlark.net@v0.0.0-20190219202100-4eb76950c5f0/starlark/value.go:653 +0x8b
     go.starlark.net/starlark.Call(0xc0000b9180, 0x16eb9e0, 0xc00013bb60, 0xc000170b80, 0x1, 0x1, 0x0, 0x0, 0x0, 0x16ec360, ...)
        go.starlark.net@v0.0.0-20190219202100-4eb76950c5f0/starlark/eval.go:1028 +0x190
     go.starlark.net/starlark.(*Function).CallInternal(0xc0000add80, 0xc0000b9180, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x101202e, 0xc0000a6e80, ...)
        go.starlark.net@v0.0.0-20190219202100-4eb76950c5f0/starlark/interp.go:305 +0x3ed8
     go.starlark.net/starlark.Call(0xc0000b9180, 0x16eba60, 0xc0000add80, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x16ec360, ...)
        go.starlark.net@v0.0.0-20190219202100-4eb76950c5f0/starlark/eval.go:1028 +0x190
     go.starlark.net/starlark.(*Function).CallInternal(0xc0000adc40, 0xc0000b9180, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc, 0xd, ...)
        go.starlark.net@v0.0.0-20190219202100-4eb76950c5f0/starlark/interp.go:305 +0x3ed8
     go.starlark.net/starlark.Call(0xc0000b9180, 0x16eba60, 0xc0000adc40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        go.starlark.net@v0.0.0-20190219202100-4eb76950c5f0/starlark/eval.go:1028 +0x190
     go.starlark.net/starlark.(*Program).Init(0xc0000ae288, 0xc0000b9180, 0xc00013ba40, 0x0, 0x0, 0xc0000ada00)
        go.starlark.net@v0.0.0-20190219202100-4eb76950c5f0/starlark/eval.go:358 +0x96
     github.com/k14s/ytt/pkg/template.(*CompiledTemplate).eval(0xc0000aaa80, 0xc0000b9180, 0xc00013ba40, 0x0, 0x0, 0x0, 0x0, 0x0)
        github.com/k14s/ytt@/pkg/template/compiled_template.go:155 +0x247
     github.com/k14s/ytt/pkg/template.(*CompiledTemplate).Eval(0xc0000aaa80, 0xc0000b9180, 0x16e2ca0, 0xc00013b020, 0xc0000b8500, 0xc0000b9180, 0xc00013b830, 0x131cefa, 0x7ffeefbff5a3)
        github.com/k14s/ytt@/pkg/template/compiled_template.go:112 +0x6c8
     github.com/k14s/ytt/pkg/workspace.(*TemplateLoader).EvalYAML(0xc00013b020, 0xc0000b8550, 0xc0000b8550, 0xc0000b8500, 0xc0000ae190, 0x1, 0x1, 0xc000089900)
        github.com/k14s/ytt@/pkg/workspace/template_loader.go:169 +0x614
     github.com/k14s/ytt/pkg/workspace.(*LibraryLoader).eval(0xc000127ad8, 0xc0000b8af0, 0x0, 0x1a57a08, 0x0, 0x0, 0xc0000b8af0, 0x0, 0x0, 0x0, ...)
        github.com/k14s/ytt@/pkg/workspace/library_loader.go:139 +0xa6c
     github.com/k14s/ytt/pkg/workspace.(*LibraryLoader).Eval(0xc000127ad8, 0xc0000b8af0, 0x0, 0x0, 0xc0000b8af0)
        github.com/k14s/ytt@/pkg/workspace/library_loader.go:90 +0x50
     github.com/k14s/ytt/pkg/cmd/template.(*TemplateOptions).RunWithFiles(0xc0000d7040, 0xc0000ae0a8, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        github.com/k14s/ytt@/pkg/cmd/template/cmd.go:131 +0x3be
     github.com/k14s/ytt/pkg/cmd/template.(*TemplateOptions).Run(0xc0000d7040, 0x0, 0x0)
        github.com/k14s/ytt@/pkg/cmd/template/cmd.go:85 +0x288
     github.com/k14s/ytt/pkg/cmd/template.NewCmd.func1(0xc000134500, 0xc0000a0c40, 0x0, 0x2, 0x0, 0x0)
        github.com/k14s/ytt@/pkg/cmd/template/cmd.go:53 +0x2a
     github.com/cppforlife/cobrautil.WrapRunEForCmd.func1.1(0xc000134500, 0xc0000a0c40, 0x0, 0x2, 0x0, 0x0)
        github.com/cppforlife/cobrautil@v0.0.0-20180924214100-a39a1714c920/misc.go:25 +0xaf
     github.com/spf13/cobra.(*Command).execute(0xc000134500, 0xc00008a190, 0x2, 0x2, 0xc000134500, 0xc00008a190)
        github.com/spf13/cobra@v0.0.3/command.go:762 +0x460
     github.com/spf13/cobra.(*Command).ExecuteC(0xc000134500, 0xc000134500, 0x1a3b0a0, 0x3)
        github.com/spf13/cobra@v0.0.3/command.go:852 +0x2ea
     github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v0.0.3/command.go:800
     main.main()
        github.com/k14s/ytt@/cmd/ytt/ytt.go:17 +0x103
     )
```

I think it would be very helpful to be able to have this possibility.
Indeed, in this case could be a solution to just split up into 2 functions. But this has also the drawback that you cannot reuse multiple doc generations throughout your templates (ex.: define a service and a deployment for K8s together in one function).

The 2nd important aspect is that you cannot call functions which generate a document from another function's body. This would also be very helpful for me to improve the templating.

**Comment by jrmyr** [comment]
Hello @pivotaljohn,

thanks for the quick reply and the proposal.

What I would like to achieve is a combination of your proposals: I want a library function which (internally) combines multiple functions/documents and returns them when I call them from another file.
The background is for example that I want to create multiple services/deployment combinations in a one-liner (not in 2 lines). It might sound not too complicated to have 2 lines, but when you have a lot of services to define, it would make things cleaner. And there also other (similar) scenarios which would benefit from that.

Form your example I understand how to combine functions within one file now. This is already a step into the right direction.
My scenario (as described above) is now:
- put the content of the `instance.yaml` into a library (without the last line)
- call the `instance` method from other files.

I tried to play a bit with the example to get this scenario working but I failed.

I hope it is clear what I mean.

**Comment by cppforlife** [comment]
@jrmyr building on what john described, here is what ive got to separate app function into a separate file: https://get-ytt.io/#gist:https://gist.github.com/cppforlife/8acaa8371bcf473b944e38055391cb2e

above example builds on these two examples: https://get-ytt.io/#example:example-load and https://get-ytt.io/#example:example-replace

**Comment by cppforlife** [comment]
do note that

```yaml
#@ load("@ytt:template", "template")

#@ def service(name):
---
kind: "Service"
metadata:
  name: #@ name
#@ end

#@ def deployment(name):
---
kind: "Deployment"
metadata:
  name: #@ name
#@ end

#@ def app(name):
--- #@ template.replace(deployment(name))
--- #@ template.replace(service(name))
#@ end
```

could be written easier as

```yaml
#@ def service(name):
kind: "Service"
metadata:
  name: #@ name
#@ end

#@ def deployment(name):
kind: "Deployment"
metadata:
  name: #@ name
#@ end

#@ def app(name):
--- #@ deployment(name)
--- #@ service(name)
#@ end
```

additionally if you looking for a more complex example, that goes beyond using individual functions for compose an app, check out https://github.com/k14s/k8s-lib#app-library

**Comment by jrmyr** [comment]
Thank you very much!
That's exactly what I was looking for.
