### ISSUE TITLE
improve error message when trying to put a docset into a document

### ISSUE THREAD

**Issue by jcfj** [k14s/ytt#212]
Input:
```ytt
#@ def two_docs():
---
doc1
---
doc2
#@ end
#! dawg
--- #@ two_docs()
```
Panic:
```
error: panic: Unexpected docset value within document

goroutine 1 [running]:
github.com/k14s/ytt/pkg/yamlmeta.convertToGo(0x9a3800, 0xc000152540, 0x7f319fa216d0, 0x0)
	github.com/k14s/ytt@/pkg/yamlmeta/convert.go:55 +0x734
github.com/k14s/ytt/pkg/yamlmeta.(*Document).AsYAMLBytes(0xc000164eb0, 0x20, 0x952800, 0xc00016d701, 0xc000176280, 0xc00016d758)
	github.com/k14s/ytt@/pkg/yamlmeta/document.go:25 +0x3c
github.com/k14s/ytt/pkg/yamlmeta.(*YAMLPrinter).Print(0xc000176280, 0xc000164eb0, 0xb25800, 0xc000176280)
	github.com/k14s/ytt@/pkg/yamlmeta/printers.go:36 +0x42
github.com/k14s/ytt/pkg/yamlmeta.(*DocumentSet).AsBytesWithPrinter(0xc0001524d0, 0xa91800, 0x1, 0x1, 0xc000094318, 0x1, 0x1)
	github.com/k14s/ytt@/pkg/yamlmeta/document_set.go:58 +0xec
github.com/k14s/ytt/pkg/yamlmeta.(*DocumentSet).AsBytes(...)
	github.com/k14s/ytt@/pkg/yamlmeta/document_set.go:43
github.com/k14s/ytt/pkg/workspace.(*LibraryLoader).Eval(0xc00016da68, 0xc00009b3c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	github.com/k14s/ytt@/pkg/workspace/library_loader.go:114 +0x33c
github.com/k14s/ytt/pkg/cmd/template.(*TemplateOptions).RunWithFiles(0xc0000b7540, 0xc000094118, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	github.com/k14s/ytt@/pkg/cmd/template/cmd.go:140 +0x4cd
github.com/k14s/ytt/pkg/cmd/template.(*TemplateOptions).Run(0xc0000b7540, 0x0, 0x0)
	github.com/k14s/ytt@/pkg/cmd/template/cmd.go:92 +0x28b
github.com/k14s/ytt/pkg/cmd/template.NewCmd.func1(0xc0000d6dc0, 0xc000120e40, 0x0, 0x3, 0x0, 0x0)
	github.com/k14s/ytt@/pkg/cmd/template/cmd.go:58 +0x2a
github.com/cppforlife/cobrautil.WrapRunEForCmd.func1.1(0xc0000d6dc0, 0xc000120e40, 0x0, 0x3, 0x0, 0x0)
	github.com/cppforlife/cobrautil@v0.0.0-20200514214827-bb86e6965d72/misc.go:45 +0xaf
github.com/cppforlife/cobrautil.WrapRunEForCmd.func1.1(0xc0000d6dc0, 0xc000120e40, 0x0, 0x3, 0x0, 0x0)
	github.com/cppforlife/cobrautil@v0.0.0-20200514214827-bb86e6965d72/misc.go:45 +0xaf
github.com/spf13/cobra.(*Command).execute(0xc0000d6dc0, 0xc00009a050, 0x3, 0x3, 0xc0000d6dc0, 0xc00009a050)
	github.com/spf13/cobra@v1.0.0/command.go:842 +0x460
github.com/spf13/cobra.(*Command).ExecuteC(0xc0000d6dc0, 0xc0000d6dc0, 0xe91480, 0xc0000a41f8)
	github.com/spf13/cobra@v1.0.0/command.go:950 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.0.0/command.go:887
main.main()
	github.com/k14s/ytt@/cmd/ytt/ytt.go:21 +0x112

```

Reproducible with `ytt version 0.30.0` and whatever is currently running on [get-ytt.io](https://get-ytt.io/)

**Comment by pivotaljohn** [comment]
In YAML, a document cannot contain another document.

From time-to-time, we _do_ want to insert multiple things — just like you are illustrating, here. 

For that there is the `template.replace()` function...

```yaml
#@ load("@ytt:template", "template")

#@ def two_docs():
---
doc1
---
doc2
#@ end
#! dawg
--- #@ template.replace(two_docs())
```

That bit if knowledge in buried, currently.  We currently only make an oblique reference at the bottom of the [Language > Functions](https://github.com/k14s/ytt/blob/7dac1c3425e719857fe5849ec22fb8910dcbafe5/docs/lang-ref-def.md) page in the documentation.

**Comment by pivotaljohn** [comment]
And yes, when we release a new version of `ytt`, the Playground on the website is automatically updated to use that latest release. 👍🏼 

I believe this is unblocked; closing. I captured the need to reduce the effort to find `template.replace()`. Please comment further if there's more here.

**Comment by jcfj** [comment]
> In YAML, a document cannot contain another document.

> For that there is the template.replace() function...

I know. Is it ok for ytt to panic in that kind of situation, though? (The panic message is not the most terrible error description, so maybe it is.)

**Comment by ewrenn8** [comment]
Yea, we probably shouldn't have a user facing panic like this. I am going to reopen the issue so we can use it to track improving the error message.
