### ISSUE TITLE
ytt should support multiple exclusion file marks

### ISSUE THREAD

**Issue by caphrim007** [k14s/ytt#368]
**What steps did you take:**

I have a directory of files and want to exclude 2 of those files.

ex:

dir/f1.yaml
dir/f2.enc.yaml
dir/f3.yaml

Content of the files can be any valid yaml

Running this command

```
ytt -f dir/ --file-mark '**/*.enc.*:exclude=true' --file-mark 'f3.yaml:exclude=true'
```

Results in the a SIGSEGV

**What happened:**

ytt crashes with the following

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x14a15e9]
goroutine 1 [running]:
github.com/k14s/ytt/pkg/files.(*File).OriginalRelativePath(...)
        github.com/k14s/ytt/pkg/files/file.go:175
github.com/k14s/ytt/pkg/cmd/template.(*FileMarksOpts).fileMarkMatches(0xc00012d5c8, 0x0, 0x7ffeefbff6a1, 0xb, 0x0)
        github.com/k14s/ytt/pkg/cmd/template/file_marks.go:133 +0x159
github.com/k14s/ytt/pkg/cmd/template.(*FileMarksOpts).Apply(0xc00012d5c8, 0xc000164680, 0xe, 0x10, 0x7, 0x8, 0x203000, 0x203000, 0x203000)
        github.com/k14s/ytt/pkg/cmd/template/file_marks.go:42 +0x29f
github.com/k14s/ytt/pkg/cmd/template.(*TemplateOptions).RunWithFiles(0xc00012d540, 0xc000164680, 0xe, 0x10, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        github.com/k14s/ytt/pkg/cmd/template/cmd.go:104 +0x8e
github.com/k14s/ytt/pkg/cmd/template.(*TemplateOptions).Run(0xc00012d540, 0x0, 0x0)
        github.com/k14s/ytt/pkg/cmd/template/cmd.go:97 +0x2b6
github.com/k14s/ytt/pkg/cmd/template.NewCmd.func1(0xc00014cdc0, 0xc000164600, 0x0, 0x8, 0x0, 0x0)
        github.com/k14s/ytt/pkg/cmd/template/cmd.go:61 +0x2a
github.com/cppforlife/cobrautil.WrapRunEForCmd.func1.1(0xc00014cdc0, 0xc000164600, 0x0, 0x8, 0x0, 0x0)
        github.com/cppforlife/cobrautil@v0.0.0-20200514214827-bb86e6965d72/misc.go:45 +0xaf
github.com/cppforlife/cobrautil.WrapRunEForCmd.func1.1(0xc00014cdc0, 0xc000164600, 0x0, 0x8, 0x0, 0x0)
        github.com/cppforlife/cobrautil@v0.0.0-20200514214827-bb86e6965d72/misc.go:45 +0xaf
github.com/spf13/cobra.(*Command).execute(0xc00014cdc0, 0xc00001e0a0, 0x8, 0x8, 0xc00014cdc0, 0xc00001e0a0)
        github.com/spf13/cobra@v1.0.0/command.go:842 +0x453
github.com/spf13/cobra.(*Command).ExecuteC(0xc00014cdc0, 0xc00014cdc0, 0x1a87b00, 0xc00011e1f8)
        github.com/spf13/cobra@v1.0.0/command.go:950 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.0.0/command.go:887
main.main()
        github.com/k14s/ytt/cmd/ytt/ytt.go:21 +0x112
```

**What did you expect:**

Would have expected yaml from f1.yaml to be printed. YAML from other 2 files to be excluded

**Anything else you would like to add:**

**Environment:**

- ytt version (use `ytt --version`): ytt version 0.31.0
- OS (e.g. from `/etc/os-release`): MacOS Big Sur

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by cppforlife** [comment]
fixed in https://github.com/vmware-tanzu/carvel-ytt/pull/369

**Comment by gcheadle-vmware** [comment]
ytt release v0.32.0 fixes this issue.
