### ISSUE TITLE
[lang] panic when using arrays within anchored content

### ISSUE THREAD

**Issue by jaresty** [k14s/ytt#46]
When trying to use a multiline comment in an anchor, ytt panics:
```
sth: &use 
  path:
  args:
  - |
    foo
here: *use
```

```
error: panic: expected len of sequence children to match len of children line nums [recovered]
	panic: expected len of sequence children to match len of children line nums

goroutine 1 [running]:
github.com/k14s/ytt/pkg/yamlmeta/internal/yaml%2ev2.handleErr(0xc00011d6a8)
	/Users/argonaut/workspace/k14s-go/src/github.com/k14s/ytt/pkg/yamlmeta/internal/yaml.v2/yaml.go:297 +0x9a
panic(0x8acac0, 0xa81900)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/k14s/ytt/pkg/yamlmeta/internal/yaml%2ev2.(*decoder).sequence(0xc000094a40, 0xc0001322a0, 0x8c8a40, 0xc0001089a0, 0x194, 0x8c8a40)
	/Users/argonaut/workspace/k14s-go/src/github.com/k14s/ytt/pkg/yamlmeta/internal/yaml.v2/decode.go:565 +0xa71
github.com/k14s/ytt/pkg/yamlmeta/internal/yaml%2ev2.(*decoder).unmarshal(0xc000094a40, 0xc0001322a0, 0x8c8a40, 0xc0001089a0, 0x194, 0x194)
	/Users/argonaut/workspace/k14s-go/src/github.com/k14s/ytt/pkg/yamlmeta/internal/yaml.v2/decode.go:344 +0x105
github.com/k14s/ytt/pkg/yamlmeta/internal/yaml%2ev2.(*decoder).mappingSlice(0xc000094a40, 0xc0001320e0, 0x8bfee0, 0xc00007acc0, 0x197, 0x197)
	/Users/argonaut/workspace/k14s-go/src/github.com/k14s/ytt/pkg/yamlmeta/internal/yaml.v2/decode.go:696 +0x4bd
github.com/k14s/ytt/pkg/yamlmeta/internal/yaml%2ev2.(*decoder).mapping(0xc000094a40, 0xc0001320e0, 0x8c8a40, 0xc000108910, 0x194, 
```

**Comment by cppforlife** [comment]
just fixed plain yaml anchoring in https://github.com/k14s/ytt/commit/2c976650426d8bcace12b542ea49f51ec1617419; however, assigning annotations to anchored content is a bit hard since currently we use line numbers and line numbers arent unique for anchored content.

**Comment by jaresty** [comment]
Is this fix live on the playground?  It still seems to be panicking when I try it out there.

**Comment by cppforlife** [comment]
@jaresty not yet. id like to polish up impl before cutting new version.

**Comment by cppforlife** [comment]
fixed in https://github.com/k14s/ytt/releases/tag/v0.17.0.
