### ISSUE TITLE
Problem with `{{}}` in template

### ISSUE THREAD

**Issue by Zanadar** [k14s/ytt#60]
Seems like there's a problem with `{{}}`.
We're experimenting with using ytt for templating our concourse pipelines.
YTT blows up with the following error:
```
Error:
- runtime error: hash of unhashable type yaml.MapSlice (backtrace: goroutine 1 [running]:
    stacks.yml:9 in <toplevel>
     L       uri: {{buildpacks-ci-git-uri-public}}
```

<details><summary>Full Stacktrace</summary>
<p>

```stacktrace
Error:
- runtime error: hash of unhashable type yaml.MapSlice (backtrace: goroutine 1 [running]:
    stacks.yml:9 in <toplevel>
     L       uri: {{buildpacks-ci-git-uri-public}}

    reason:
     runtime/debug.Stack(0x14ec820, 0x14e69c0, 0xc0000b8090)
     	/usr/local/go/src/runtime/debug/stack.go:24 +0x9d
     github.com/k14s/ytt/pkg/template/core.ErrWrapper.func1.1(0xc0004e6ba0)
     	/Users/argonaut/workspace/k14s-go/src/github.com/k14s/ytt/pkg/template/core/errs.go:18 +0x9d
     panic(0x14e69c0, 0xc0000b8090)
     	/usr/local/go/src/runtime/panic.go:522 +0x1b5
     github.com/k14s/ytt/pkg/yamltemplate.MapItemOverride.Apply(0xc0004085f0, 0xc000408690, 0xc0004e6908, 0xb)
     	/Users/argonaut/workspace/k14s-go/src/github.com/k14s/ytt/pkg/yamltemplate/map_key_overrides.go:26 +0x138
     github.com/k14s/ytt/pkg/yamltemplate.EvaluationCtx.PrepareNode(0x16ad880, 0xc0004085f0, 0x16ad8e0, 0xc000408690, 0x12, 0xc000096300)
     	/Users/argonaut/workspace/k14s-go/src/github.com/k14s/ytt/pkg/yamltemplate/evaluation_ctx.go:24 +0x71
     github.com/k14s/ytt/pkg/template.(*EvaluationCtx).startNode(0xc000128000, 0x13, 0x13, 0x0)
     	/Users/argonaut/workspace/k14s-go/src/github.com/k14s/ytt/pkg/template/evaluation_ctx.go:191 +0x1bc
     github.com/k14s/ytt/pkg/template.(*EvaluationCtx).TplStartNode(0xc000128000, 0xc0000dcff0, 0xc000143a40, 0xc000155ff0, 0x1, 0x1, 0x0, 0x0, 0x0, 0x8, ...)
     	/Users/argonaut/workspace/k14s-go/src/github.com/k14s/ytt/pkg/template/evaluation_ctx.go:157 +0x179
     github.com/k14s/ytt/pkg/template.(*CompiledTemplate).tplStartNode(...)
     	/Users/argonaut/workspace/k14s-go/src/github.com/k14s/ytt/pkg/template/compiled_template.go:241
     github.com/k14s/ytt/pkg/template/core.ErrWrapper.func1(0xc0000dcff0, 0xc000143a40, 0xc000155ff0, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
     	/Users/argonaut/workspace/k14s-go/src/github.com/k14s/ytt/pkg/template/core/errs.go:25 +0xe9
     github.com/k14s/ytt/vendor/go.starlark.net/starlark.(*Builtin).CallInternal(0xc000143a40, 0xc0000dcff0, 0xc000155ff0, 0x1, 0x1, 0x0, 0x0, 0x0, 0x16ab320, 0x10, ...)
     	/Users/argonaut/workspace/k14s-go/src/github.com/k14s/ytt/vendor/go.starlark.net/starlark/value.go:653 +0x8b
     github.com/k14s/ytt/vendor/go.starlark.net/starlark.Call(0xc0000dcff0, 0x16aaa20, 0xc000143a40, 0xc000155ff0, 0x1, 0x1, 0x0, 0x0, 0x0, 0x16ab320, ...)
     	/Users/argonaut/workspace/k14s-go/src/github.com/k14s/ytt/vendor/go.starlark.net/starlark/eval.go:1028 +0x19f
     github.com/k14s/ytt/vendor/go.starlark.net/starlark.(*Function).CallInternal(0xc0004d3200, 0xc0000dcff0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x13e88b7, 0x152ac40, ...)
     	/Users/argonaut/workspace/k14s-go/src/github.com/k14s/ytt/vendor/go.starlark.net/starlark/interp.go:305 +0x4550
     github.com/k14s/ytt/vendor/go.starlark.net/starlark.Call(0xc0000dcff0, 0x16aaaa0, 0xc0004d3200, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1, ...)
     	/Users/argonaut/workspace/k14s-go/src/github.com/k14s/ytt/vendor/go.starlark.net/starlark/eval.go:1028 +0x19f
     github.com/k14s/ytt/vendor/go.starlark.net/starlark.(*Program).Init(0xc0004ba018, 0xc0000dcff0, 0xc000143950, 0x0, 0x0, 0xc0004d2e80)
     	/Users/argonaut/workspace/k14s-go/src/github.com/k14s/ytt/vendor/go.starlark.net/starlark/eval.go:358 +0x96
     github.com/k14s/ytt/pkg/template.(*CompiledTemplate).eval(0xc0004b2060, 0xc0000dcff0, 0xc000143950, 0x0, 0x0, 0x0, 0x0, 0x0)
     	/Users/argonaut/workspace/k14s-go/src/github.com/k14s/ytt/pkg/template/compiled_template.go:140 +0x203
     github.com/k14s/ytt/pkg/template.(*CompiledTemplate).Eval(0xc0004b2060, 0xc0000dcff0, 0x16a9360, 0xc0001fca20, 0xc0000dcff0, 0xc0001438f0, 0xc0001299d0, 0x0, 0x0)
     	/Users/argonaut/workspace/k14s-go/src/github.com/k14s/ytt/pkg/template/compiled_template.go:101 +0x719
     github.com/k14s/ytt/pkg/workspace.(*TemplateLoader).EvalYAML(0xc0001fca20, 0xc0000dc3c0, 0xc0000dc370, 0x0, 0xc00015ae60, 0x1, 0x1)
     	/Users/argonaut/workspace/k14s-go/src/github.com/k14s/ytt/pkg/workspace/template_loader.go:172 +0x8be
     github.com/k14s/ytt/pkg/workspace.(*LibraryLoader).eval(0xc0004e7b68, 0x14d6ee0, 0xc0001fc9f0, 0x0, 0x0, 0xc00020f090, 0x0, 0x0, 0x100dca8)
     	/Users/argonaut/workspace/k14s-go/src/github.com/k14s/ytt/pkg/workspace/library_loader.go:126 +0x6c4
     github.com/k14s/ytt/pkg/workspace.(*LibraryLoader).Eval(0xc0004e7b68, 0x14d6ee0, 0xc0001fc9f0, 0x14d6ee0, 0xc0001fc9f0, 0x0)
     	/Users/argonaut/workspace/k14s-go/src/github.com/k14s/ytt/pkg/workspace/library_loader.go:82 +0x5d
     github.com/k14s/ytt/pkg/cmd/template.(*TemplateOptions).RunWithFiles(0xc000150000, 0xc0000b2048, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
     	/Users/argonaut/workspace/k14s-go/src/github.com/k14s/ytt/pkg/cmd/template/cmd.go:118 +0x20d
     github.com/k14s/ytt/pkg/cmd/template.(*TemplateOptions).Run(0xc000150000, 0x0, 0x0)
     	/Users/argonaut/workspace/k14s-go/src/github.com/k14s/ytt/pkg/cmd/template/cmd.go:83 +0x255
     github.com/k14s/ytt/pkg/cmd/template.NewCmd.func1(0xc000152000, 0xc00014a2c0, 0x0, 0x2, 0x0, 0x0)
     	/Users/argonaut/workspace/k14s-go/src/github.com/k14s/ytt/pkg/cmd/template/cmd.go:53 +0x2a
     github.com/k14s/ytt/vendor/github.com/cppforlife/cobrautil.WrapRunEForCmd.func1.1(0xc000152000, 0xc00014a2c0, 0x0, 0x2, 0x0, 0x0)
     	/Users/argonaut/workspace/k14s-go/src/github.com/k14s/ytt/vendor/github.com/cppforlife/cobrautil/misc.go:25 +0xaf
     github.com/k14s/ytt/vendor/github.com/spf13/cobra.(*Command).execute(0xc000152000, 0xc0000b6010, 0x2, 0x2, 0xc000152000, 0xc0000b6010)
     	/Users/argonaut/workspace/k14s-go/src/github.com/k14s/ytt/vendor/github.com/spf13/cobra/command.go:762 +0x465
     github.com/k14s/ytt/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc000152000, 0xc000152000, 0x1a227e0, 0xc0000f3f58)
     	/Users/argonaut/workspace/k14s-go/src/github.com/k14s/ytt/vendor/github.com/spf13/cobra/command.go:852 +0x2ec
     github.com/k14s/ytt/vendor/github.com/spf13/cobra.(*Command).Execute(...)
     	/Users/argonaut/workspace/k14s-go/src/github.com/k14s/ytt/vendor/github.com/spf13/cobra/command.go:800
     main.main()
     	/Users/argonaut/workspace/k14s-go/src/github.com/k14s/ytt/cmd/ytt/ytt.go:17 +0x10b
```
</p>
</details>

And excertpy of the YAML in question:
```yaml
#@ load("@ytt:data", "data")

---
resources:
  #! Github Repos
  - name: buildpacks-ci
    type: git
    source:
      uri: {{buildpacks-ci-git-uri-public}}
      branch: master

```

**Comment by Zanadar** [comment]
Update: Quoting works. Closing.
